
DROP TABLE TB_CUSTOMER;

CREATE TABLE TB_CUSTOMER(
	ID VARCHAR2(100) PRIMARY KEY,
	PASSWORD VARCHAR2(1000) NOT NULL,
	NAME VARCHAR2(100) NOT NULL
);

INSERT INTO TB_CUSTOMER VALUES('admin', 'admin1234', '관리자');

SELECT ID, PW, NAME FROM TB_CUSTOMER;	
